package com.rw.carriages.dao;

public interface SQLQueries {
    String CARRIAGE_IMAGE = "SELECT GRAPHIC_MODEL FROM ETICKET.CARRIAGE_MODELS WHERE ID=:ID";
    String FORCED_ER = "SELECT TRAIN_NO FROM ETICKET.TRAINS_WITH_FORCED_ER WHERE TRAIN_NO LIKE :TRAIN_NO AND (DATE_FROM IS NULL OR DATE_FROM>=CURRENT_DATE) AND (DATE_TO IS NULL OR DATE_TO<=CURRENT_DATE)";
    String CHECK_RETURN_FORBIDDEN = "SELECT ID FROM ETICKET.TRAINS_WITH_FORBIDDEN_RETURN WHERE TRAIN_NO LIKE :TRAIN_NO AND CARRIAGE_TYPE = :CARRIAGE_TYPE";
    String GRAPHIC_CARRIGAGE_SIGNS = "SELECT ID,CARRIAGE_SIGN FROM ETICKET.CARRIAGE_CELL_SIGNS WITH UR";

    String MODEL_BY_TRAIN_SCHEME = "SELECT t2.IS_ACTIVE,t1.ID, t1.CARRIAGE_ID,t1.GRAPHIC_MODEL_WIDTH,t1.GRAPHIC_MODEL_HEIGHT,t1.SEAT_WIDTH,t1.SEAT_HEIGHT,t1.MODEL_SIGN_COORDINATES,t3.MODEL_SEAT_COORDINATES,t2.FIRST_SEAT,t2.LAST_SEAT FROM " +
            "ETICKET.TRAIN_SCHEME_REGULARITY t5 " +
            "JOIN ETICKET.TRAIN_SCHEME_CARRIAGES t6 ON t6.TRAIN_SCHEME_ID=t5.TRAIN_SCHEME_ID AND t6.CARRIAGE_NUMBER=:CARRIAGE_NUMBER " +
            "JOIN ETICKET.CARRIAGES t2 ON t6.CARRIAGE_ID = t2.ID " +
            "LEFT JOIN ETICKET.CARRIAGE_MODEL_SEAT_COORDINATES t3 ON t3.CARRIAGE_ID=t2.ID " +
            "JOIN ETICKET.CARRIAGE_TYPES t4 ON t4.ID=t2.CARRIAGE_TYPE_ID AND t4.CODE=:CARRIAGE_TYPE_CODE " +
            "LEFT JOIN ETICKET.CARRIAGE_MODELS t1 ON t1.CARRIAGE_ID=t2.ID " +
            "WHERE t5.TRAIN_NO = :TRAIN_NO AND (t5.DATE_FROM IS NULL OR t5.DATE_FROM<=:DATE) AND (t5.DATE_TO IS NULL OR t5.DATE_TO>=:DATE) AND (t5.REGULARITY IS NULL OR t5.REGULARITY LIKE :DAY_NUM OR t5.REGULARITY LIKE :DAY_TYPE) AND t2.IS_STANDARD=:IS_STANDARD ORDER BY t2.IS_ACTIVE DESC FETCH FIRST ROW ONLY WITH UR";

    String MODEL_BY_SUBTYPE = "SELECT t2.IS_ACTIVE,t1.ID, t1.CARRIAGE_ID, t1.GRAPHIC_MODEL_WIDTH,t1.GRAPHIC_MODEL_HEIGHT,t1.SEAT_WIDTH,t1.SEAT_HEIGHT,t1.MODEL_SIGN_COORDINATES,t3.MODEL_SEAT_COORDINATES,t2.FIRST_SEAT,t2.LAST_SEAT FROM ETICKET.CARRIAGE_MODELS t1 JOIN ETICKET.CARRIAGES t2 ON t1.CARRIAGE_ID=t2.ID JOIN ETICKET.CARRIAGE_MODEL_SEAT_COORDINATES t3 ON t3.CARRIAGE_ID=t2.ID JOIN ETICKET.CARRIAGE_TYPES t4 ON t4.ID=t2.CARRIAGE_TYPE_ID " +
            "WHERE t4.CODE=:CARRIAGE_TYPE_CODE AND t2.CARRIAGE_SUBTYPE=:CARRIAGE_SUBTYPE AND t2.IS_STANDARD=:IS_STANDARD ORDER BY t2.IS_ACTIVE DESC FETCH FIRST ROW ONLY WITH UR";
    String MODEL_BY_SEATS_STRICT = "SELECT t2.IS_ACTIVE,t1.ID, t1.CARRIAGE_ID, t1.GRAPHIC_MODEL_WIDTH,t1.GRAPHIC_MODEL_HEIGHT,t1.SEAT_WIDTH,t1.SEAT_HEIGHT,t1.MODEL_SIGN_COORDINATES,t3.MODEL_SEAT_COORDINATES,t2.FIRST_SEAT,t2.LAST_SEAT FROM ETICKET.CARRIAGE_MODELS t1 JOIN ETICKET.CARRIAGES t2 ON t1.CARRIAGE_ID=t2.ID JOIN ETICKET.CARRIAGE_MODEL_SEAT_COORDINATES t3 ON t3.CARRIAGE_ID=t2.ID JOIN ETICKET.CARRIAGE_TYPES t4 ON t4.ID=t2.CARRIAGE_TYPE_ID " +
            "WHERE t4.CODE=:CARRIAGE_TYPE_CODE AND t2.LAST_SEAT=:LAST_SEAT AND t2.IS_STANDARD=:IS_STANDARD AND (t2.SERVICE_CLASSES IS NULL OR t2.SERVICE_CLASSES=:EMPTY OR t2.SERVICE_CLASSES LIKE :SERVICE_CLASS) AND (:SEAT_COUNT=0 OR :SEAT_COUNT<>0 AND t2.SEAT_COUNT>t2.LAST_SEAT) ORDER BY t2.IS_ACTIVE DESC FETCH FIRST ROW ONLY WITH UR";

    String MODEL_BY_SEATS_STRICT_SPECIAL = "SELECT DISTINCT t2.IS_ACTIVE,t1.ID, t1.CARRIAGE_ID, t1.GRAPHIC_MODEL_WIDTH,t1.GRAPHIC_MODEL_HEIGHT,t1.SEAT_WIDTH,t1.SEAT_HEIGHT,t1.MODEL_SIGN_COORDINATES,t3.MODEL_SEAT_COORDINATES,t2.FIRST_SEAT,t2.LAST_SEAT FROM ETICKET.CARRIAGE_MODELS t1 JOIN ETICKET.CARRIAGES t2 ON t1.CARRIAGE_ID=t2.ID JOIN ETICKET.CARRIAGE_MODEL_SEAT_COORDINATES t3 ON t3.CARRIAGE_ID=t2.ID JOIN ETICKET.CARRIAGE_TYPES t4 ON t4.ID=t2.CARRIAGE_TYPE_ID " +
            "JOIN  ETICKET.CARRIAGE_SEAT_LAYOUTS cl ON cl.CARRIAGE_ID = t1.CARRIAGE_ID AND cl.ANCHOR_SERVICE_CLASS LIKE :SERVICE_CLASS "+
            "WHERE t4.CODE=:CARRIAGE_TYPE_CODE AND t2.LAST_SEAT=:LAST_SEAT AND t2.IS_STANDARD=:IS_STANDARD AND (t2.SERVICE_CLASSES IS NULL OR t2.SERVICE_CLASSES=:EMPTY OR t2.SERVICE_CLASSES LIKE :SERVICE_CLASS) AND (:SEAT_COUNT=0 OR :SEAT_COUNT<>0 AND t2.SEAT_COUNT>t2.LAST_SEAT) ORDER BY t2.IS_ACTIVE DESC FETCH FIRST ROW ONLY WITH UR";

    String MODEL_BY_SEATS_STRICT_NEAREST = "SELECT t2.IS_ACTIVE,t1.ID, t1.CARRIAGE_ID, t1.GRAPHIC_MODEL_WIDTH,t1.GRAPHIC_MODEL_HEIGHT,t1.SEAT_WIDTH,t1.SEAT_HEIGHT,t1.MODEL_SIGN_COORDINATES,t3.MODEL_SEAT_COORDINATES,t2.FIRST_SEAT,t2.LAST_SEAT FROM ETICKET.CARRIAGE_MODELS t1 JOIN ETICKET.CARRIAGES t2 ON t1.CARRIAGE_ID=t2.ID JOIN ETICKET.CARRIAGE_MODEL_SEAT_COORDINATES t3 ON t3.CARRIAGE_ID=t2.ID JOIN ETICKET.CARRIAGE_TYPES t4 ON t4.ID=t2.CARRIAGE_TYPE_ID " +
            "WHERE t4.CODE=:CARRIAGE_TYPE_CODE AND t2.LAST_SEAT>:LAST_SEAT AND t2.LAST_SEAT<(:LAST_SEAT + 10) AND t2.IS_STANDARD=:IS_STANDARD AND (t2.SERVICE_CLASSES IS NULL OR t2.SERVICE_CLASSES=:EMPTY OR t2.SERVICE_CLASSES LIKE :SERVICE_CLASS) AND (:SEAT_COUNT=0 AND t2.SEAT_COUNT<=t2.LAST_SEAT OR :SEAT_COUNT<>0 AND t2.SEAT_COUNT>t2.LAST_SEAT) ORDER BY t2.IS_ACTIVE DESC, t2.LAST_SEAT ASC FETCH FIRST ROW ONLY WITH UR";

    String GRAPHIC_CARRIAGE_SEAT_LAYOUTS = "SELECT * FROM ETICKET.CARRIAGE_SEAT_LAYOUTS WHERE CARRIAGE_ID=:CARRIAGE_ID AND ANCHOR_SERVICE_CLASS LIKE :SERVICE_CLASS AND CARRIAGE_SERVICE_CLASS IN (:CARRIAGE_SERVICE_CLASSES) ORDER BY IS_FULL_PLACES DESC";
    String GRAPHIC_CARRIAGE_SEATS = "SELECT * FROM ETICKET.CARRIAGE_SEATS WHERE CARRIAGE_ID=:CARRIAGE_ID";

    String TRAVEL_DIRECTION = "SELECT TRAVEL_DIRECTION FROM ETICKET.TRAINS WHERE TRAIN_NO=:TRAIN_NO";

}
